Attribute VB_Name = "Globals"
Option Explicit

Public lngNextPort As Long

Public Const HDS_BUTTONS As Long = &H2
Public Const LVM_FIRST As Long = &H1000
Public Const LVM_GETHEADER As Long = (LVM_FIRST + 31)
Public Const GWL_STYLE As Long = (-16)
Public Const SWP_DRAWFRAME As Long = &H20
Public Const SWP_NOMOVE As Long = &H2
Public Const SWP_NOSIZE As Long = &H1
Public Const SWP_NOZORDER As Long = &H4
Public Const SWP_FLAGS As Long = SWP_NOZORDER Or _
                                 SWP_NOSIZE Or _
                                 SWP_NOMOVE Or _
                                 SWP_DRAWFRAME
  
Public Declare Function SendMessage Lib "USER32" _
    Alias "SendMessageA" _
   (ByVal hWnd As Long, _
    ByVal Msg As Long, _
    ByVal wParam As Long, _
    lParam As Any) As Long

Public Declare Function GetWindowLong Lib "USER32" _
   Alias "GetWindowLongA" _
   (ByVal hWnd As Long, _
   ByVal nIndex As Long) As Long
   
Public Declare Function SetWindowLong Lib "USER32" _
   Alias "SetWindowLongA" _
   (ByVal hWnd As Long, _
   ByVal nIndex As Long, _
   ByVal dwNewLong As Long) As Long
   
Public Declare Function SetWindowPos Lib "USER32" _
   (ByVal hWnd As Long, ByVal hWndInsertAfter As Long, _
    ByVal x As Long, ByVal Y As Long, _
    ByVal cx As Long, ByVal cy As Long, _
    ByVal wFlags As Long) As Long


Public Function portname(theport)
If theport = 1 Then portname = "TCP Port Service Multiplexer"
If theport = 2 Then portname = "Management Utility"
If theport = 3 Then portname = "Compression Process"
If theport = 5 Then portname = "Remote Job Entry"
If theport = 7 Then portname = "Echo"
If theport = 9 Then portname = "Discard"
If theport = 11 Then portname = "Active Users"
If theport = 13 Then portname = "Daytime"
If theport = 17 Then portname = "Quote of the Day"
If theport = 18 Then portname = "Message Send Protocol"
If theport = 19 Then portname = "Character Generator"
If theport = 20 Then portname = "File Transfer [Default Data]"
If theport = 21 Then portname = "File Transfer Protocol [Control]"
If theport = 22 Then portname = "SSH Remote Login Protocol"
If theport = 23 Then portname = "Telnet"
If theport = 24 Then portname = "any private mail system"
If theport = 25 Then portname = "Simple Mail Transfer"
If theport = 27 Then portname = "NSW User System FE"
If theport = 29 Then portname = "MSG ICP"
If theport = 31 Then portname = "MSG Authentication"
If theport = 33 Then portname = "Display Support Protocol"
If theport = 35 Then portname = "any private printer server"
If theport = 37 Then portname = "Time"
If theport = 38 Then portname = "Route Access Protocol"
If theport = 39 Then portname = "Resource Location Protocol"
If theport = 41 Then portname = "Graphics"
If theport = 42 Then portname = "WINS Host Name Server"
If theport = 43 Then portname = "Who Is"
If theport = 44 Then portname = "MPM FLAGS Protocol"
If theport = 45 Then portname = "Message Processing Module [recv]"
If theport = 46 Then portname = "MPM [default send]"
If theport = 47 Then portname = "NI FTP"
If theport = 48 Then portname = "Digital Audit Daemon"
If theport = 49 Then portname = "Login Host Protocol (TACACS)"
If theport = 50 Then portname = "Remote Mail Checking Protocol"
If theport = 51 Then portname = "IMP Logical Address Maintenance"
If theport = 52 Then portname = "XNS Time Protocol"
If theport = 53 Then portname = "Domain Name Server"
If theport = 54 Then portname = "XNS Clearinghouse"
If theport = 55 Then portname = "ISI Graphics Language"
If theport = 56 Then portname = "XNS Authentication"
If theport = 57 Then portname = "any private terminal access"
If theport = 58 Then portname = "XNS Mail"
If theport = 59 Then portname = "any private file service"
If theport = 60 Then portname = "Unassigned"
If theport = 61 Then portname = "NI MAIL"
If theport = 62 Then portname = "ACA Services"
If theport = 63 Then portname = "whois"
If theport = 64 Then portname = "Communications Integrator (CI)"
If theport = 65 Then portname = "TACACS-Database Service"
If theport = 66 Then portname = "Oracle SQL*NET"
If theport = 67 Then portname = "Bootstrap Protocol Server"
If theport = 68 Then portname = "Bootstrap Protocol Client"
If theport = 69 Then portname = "Trivial File Transfer"
If theport = 70 Then portname = "Gopher"
If theport = 71 Then portname = "Remote Job Service"
If theport = 72 Then portname = "Remote Job Service"
If theport = 73 Then portname = "Remote Job Service"
If theport = 74 Then portname = "Remote Job Service"
If theport = 75 Then portname = "any private dial out service"
If theport = 76 Then portname = "Distributed External Object Store"
If theport = 77 Then portname = "any private RJE service"
If theport = 78 Then portname = "vettcp"
If theport = 79 Then portname = "Finger"
If theport = 80 Then portname = "World Wide Web HTTP"
If theport = 81 Then portname = "HOSTS2 Name Server"
If theport = 82 Then portname = "XFER Utility"
If theport = 83 Then portname = "MIT ML Device"
If theport = 84 Then portname = "Common Trace Facility"
If theport = 85 Then portname = "MIT ML Device"
If theport = 86 Then portname = "Micro Focus Cobol"
If theport = 87 Then portname = "any private terminal link"
If theport = 88 Then portname = "Kerberos"
If theport = 89 Then portname = "SU/MIT Telnet Gateway"
If theport = 90 Then portname = "DNSIX Securit Attribute Token Map"
If theport = 91 Then portname = "MIT Dover Spooler"
If theport = 92 Then portname = "Network Printing Protocol"
If theport = 93 Then portname = "Device Control Protocol"
If theport = 94 Then portname = "Tivoli Object Dispatcher"
If theport = 95 Then portname = "SUPDUP"
If theport = 96 Then portname = "DIXIE Protocol Specification"
If theport = 97 Then portname = "Swift Remote Virtural File Protocol"
If theport = 98 Then portname = "TAC News"
If theport = 99 Then portname = "Metagram Relay"
If theport = 100 Then portname = "[unauthorized use]"
If theport = 101 Then portname = "NIC Host Name Server"
If theport = 102 Then portname = "ISO-TSAP Class 0"
If theport = 103 Then portname = "Genesis Point-to-Point Trans Net"
If theport = 104 Then portname = "ACR-NEMA Digital Imag. & Comm. 300"
If theport = 105 Then portname = "CCSO name server protocol"
If theport = 106 Then portname = "3COM-TSMUX"
If theport = 107 Then portname = "Remote Telnet Service"
If theport = 108 Then portname = "SNA Gateway Access Server"
If theport = 109 Then portname = "Post Office Protocol - Version 2"
If theport = 110 Then portname = "Post Office Protocol - Version 3"
If theport = 111 Then portname = "SUN Remote Procedure Call"
If theport = 112 Then portname = "McIDAS Data Transmission Protocol"
If theport = 113 Then portname = "Authentication Service"
If theport = 114 Then portname = "Audio News Multicast"
If theport = 115 Then portname = "Simple File Transfer Protocol"
If theport = 116 Then portname = "ANSA REX Notify"
If theport = 117 Then portname = "UUCP Path Service"
If theport = 118 Then portname = "SQL Services"
If theport = 119 Then portname = "Network News Transfer Protocol"
If theport = 120 Then portname = "CFDPTKT"
If theport = 121 Then portname = "Encore Expedited Remote Pro.Call"
If theport = 122 Then portname = "SMAKYNET"
If theport = 123 Then portname = "Network Time Protocol"
If theport = 124 Then portname = "ANSA REX Trader"
If theport = 125 Then portname = "Locus PC-Interface Net Map Ser"
If theport = 126 Then portname = "Unisys Unitary Login"
If theport = 127 Then portname = "Locus PC-Interface Conn Server"
If theport = 128 Then portname = "GSS X License Verification"
If theport = 129 Then portname = "Password Generator Protocol"
If theport = 130 Then portname = "cisco FNATIVE"
If theport = 131 Then portname = "cisco TNATIVE"
If theport = 132 Then portname = "cisco SYSMAINT"
If theport = 133 Then portname = "Statistics Service"
If theport = 134 Then portname = "INGRES-NET Service"
If theport = 135 Then portname = "DCE endpoint resolution"
If theport = 136 Then portname = "PROFILE Naming System"
If theport = 137 Then portname = "NETBIOS Name Service"
If theport = 138 Then portname = "NETBIOS Datagram Service"
If theport = 139 Then portname = "NETBIOS Session Service"
If theport = 140 Then portname = "EMFIS Data Service"
If theport = 141 Then portname = "EMFIS Control Service"
If theport = 142 Then portname = "Britton-Lee IDM"
If theport = 143 Then portname = "Internet Message Access Protocol"
If theport = 144 Then portname = "NewS"
If theport = 145 Then portname = "UAAC Protocol"
If theport = 146 Then portname = "ISO-IP0"
If theport = 147 Then portname = "ISO-IP"
If theport = 148 Then portname = "Jargon"
If theport = 149 Then portname = "AED 512 Emulation Service"
If theport = 150 Then portname = "SQL-NET"
If theport = 151 Then portname = "HEMS"
If theport = 152 Then portname = "Background File Transfer Program"
If theport = 153 Then portname = "SGMP"
If theport = 154 Then portname = "NETSC"
If theport = 155 Then portname = "NETSC"
If theport = 156 Then portname = "SQL Service"
If theport = 157 Then portname = "KNET/VM Command/Message Protocol"
If theport = 158 Then portname = "PCMail Server"
If theport = 159 Then portname = "NSS-Routing"
If theport = 160 Then portname = "SGMP-TRAPS"
If theport = 161 Then portname = "SNMP"
If theport = 162 Then portname = "SNMPTRAP"
If theport = 163 Then portname = "CMIP Manager"
If theport = 164 Then portname = "CMIP Agent"
If theport = 165 Then portname = "Xerox"
If theport = 166 Then portname = "Sirius Systems"
If theport = 167 Then portname = "NAMP"
If theport = 168 Then portname = "RSVD"
If theport = 169 Then portname = "SEND"
If theport = 170 Then portname = "Network PostScript"
If theport = 171 Then portname = "Network Innovations Multiplex"
If theport = 172 Then portname = "Network Innovations CL/1"
If theport = 173 Then portname = "Xyplex"
If theport = 174 Then portname = "MAILQ"
If theport = 175 Then portname = "VMNET"
If theport = 176 Then portname = "GENRAD-MUX"
If theport = 177 Then portname = "X Display Manager Control Protocol"
If theport = 178 Then portname = "NextStep Window Server"
If theport = 179 Then portname = "Border Gateway Protocol"
If theport = 180 Then portname = "Intergraph"
If theport = 181 Then portname = "Unify"
If theport = 182 Then portname = "Unisys Audit SITP"
If theport = 183 Then portname = "OCBinder"
If theport = 184 Then portname = "OCServer"
If theport = 185 Then portname = "Remote-KIS"
If theport = 186 Then portname = "KIS Protocol"
If theport = 187 Then portname = "Application Communication Interface"
If theport = 188 Then portname = "Plus Five's MUMPS"
If theport = 189 Then portname = "Queued File Transport"
If theport = 190 Then portname = "Gateway Access Control Protocol"
If theport = 191 Then portname = "Prospero Directory Service"
If theport = 192 Then portname = "OSU Network Monitoring System"
If theport = 193 Then portname = "Spider Remote Monitoring Protocol"
If theport = 194 Then portname = "Internet Relay Chat Protocol"
If theport = 195 Then portname = "DNSIX Network Level Module Audit"
If theport = 196 Then portname = "DNSIX Session Mgt Module Audit Redir"
If theport = 197 Then portname = "Directory Location Service"
If theport = 198 Then portname = "Directory Location Service Monitor"
If theport = 199 Then portname = "SMUX"
If theport = 200 Then portname = "IBM System Resource Controller"
If theport = 201 Then portname = "AppleTalk Routing Maintenance"
If theport = 202 Then portname = "AppleTalk Name Binding"
If theport = 203 Then portname = "AppleTalk Unused"
If theport = 204 Then portname = "AppleTalk Echo"
If theport = 205 Then portname = "AppleTalk Unused"
If theport = 206 Then portname = "AppleTalk Zone Information"
If theport = 207 Then portname = "AppleTalk Unused"
If theport = 208 Then portname = "AppleTalk Unused"
If theport = 209 Then portname = "The Quick Mail Transfer Protocol"
If theport = 210 Then portname = "ANSI Z39.50"
If theport = 211 Then portname = "Texas Instruments 914C/G Terminal"
If theport = 212 Then portname = "ATEXSSTR"
If theport = 213 Then portname = "IPX"
If theport = 214 Then portname = "VM PWSCS"
If theport = 215 Then portname = "Insignia Solutions"
If theport = 216 Then portname = "Computer Associates Int'l License Server"
If theport = 217 Then portname = "dBASE Unix"
If theport = 218 Then portname = "Netix Message Posting Protocol"
If theport = 219 Then portname = "Unisys ARPs"
If theport = 220 Then portname = "Interactive Mail Access Protocol v3"
If theport = 221 Then portname = "Berkeley rlogind with SPX auth"
If theport = 222 Then portname = "Berkeley rshd with SPX auth"
If theport = 223 Then portname = "Certificate Distribution Center"
If theport = 242 Then portname = "Direct"
If theport = 243 Then portname = "Survey Measurement"
If theport = 244 Then portname = "Dayna"
If theport = 245 Then portname = "LINK"
If theport = 246 Then portname = "Display Systems Protocol"
If theport = 256 Then portname = "RAP"
If theport = 257 Then portname = "Secure Electronic Transaction"
If theport = 258 Then portname = "Yak Winsock Personal Chat"
If theport = 259 Then portname = "Efficient Short Remote Operations"
If theport = 260 Then portname = "Openport"
If theport = 261 Then portname = "IIOP Naming Service (SSL)"
If theport = 262 Then portname = "Arcisdms"
If theport = 263 Then portname = "HDAP"
If theport = 280 Then portname = "http-mgmt"
If theport = 281 Then portname = "Personal Link"
If theport = 282 Then portname = "Cable Port A/X"
If theport = 309 Then portname = "EntrustTime"
If theport = 344 Then portname = "Prospero Data Access Protocol"
If theport = 345 Then portname = "Perf Analysis Workbench"
If theport = 346 Then portname = "Zebra server"
If theport = 347 Then portname = "Fatmen Server"
If theport = 348 Then portname = "Cabletron Management Protocol"
If theport = 349 Then portname = "mftp"
If theport = 350 Then portname = "MATIP Type A"
If theport = 351 Then portname = "MATIP Type B"
If theport = 371 Then portname = "Clearcase"
If theport = 372 Then portname = "ListProcessor"
If theport = 373 Then portname = "Legent Corporation"
If theport = 374 Then portname = "Legent Corporation"
If theport = 375 Then portname = "Hassle"
If theport = 376 Then portname = "Amiga Envoy Network Inquiry Proto"
If theport = 377 Then portname = "NEC Corporation"
If theport = 378 Then portname = "NEC Corporation"
If theport = 379 Then portname = "TIA/EIA/IS-99 modem client"
If theport = 380 Then portname = "TIA/EIA/IS-99 modem server"
If theport = 381 Then portname = "hp performance data collector"
If theport = 382 Then portname = "hp performance data managed node"
If theport = 383 Then portname = "hp performance data alarm manager"
If theport = 384 Then portname = "A Remote Network Server System"
If theport = 385 Then portname = "IBM Application"
If theport = 386 Then portname = "ASA Message Router Object Def."
If theport = 387 Then portname = "Appletalk Update-Based Routing Pro."
If theport = 388 Then portname = "Unidata LDM Version 4"
If theport = 389 Then portname = "Lightweight Directory Access Protocol"
If theport = 390 Then portname = "UIS"
If theport = 391 Then portname = "SynOptics SNMP Relay Port"
If theport = 392 Then portname = "SynOptics Port Broker Port"
If theport = 393 Then portname = "Data Interpretation System"
If theport = 394 Then portname = "EMBL Nucleic Data Transfer"
If theport = 395 Then portname = "NETscout Control Protocol"
If theport = 396 Then portname = "Novell Netware over IP"
If theport = 397 Then portname = "Multi Protocol Trans. Net."
If theport = 398 Then portname = "Kryptolan"
If theport = 399 Then portname = "ISO Transport Class 2 Non-Control over TCP"
If theport = 400 Then portname = "Workstation Solutions"
If theport = 401 Then portname = "Uninterruptible Power Supply"
If theport = 402 Then portname = "Genie Protocol"
If theport = 403 Then portname = "decap"
If theport = 404 Then portname = "nced"
If theport = 405 Then portname = "ncld"
If theport = 406 Then portname = "Interactive Mail Support Protocol"
If theport = 407 Then portname = "Timbuktu"
If theport = 408 Then portname = "Prospero Resource Manager Sys. Man."
If theport = 409 Then portname = "Prospero Resource Manager Node Man."
If theport = 410 Then portname = "DECLadebug Remote Debug Protocol"
If theport = 411 Then portname = "Remote MT Protocol"
If theport = 412 Then portname = "Trap Convention Port"
If theport = 413 Then portname = "SMSP"
If theport = 414 Then portname = "InfoSeek"
If theport = 415 Then portname = "BNet"
If theport = 416 Then portname = "Silverplatter"
If theport = 417 Then portname = "Onmux"
If theport = 418 Then portname = "Hyper-G"
If theport = 419 Then portname = "Ariel"
If theport = 420 Then portname = "SMPTE"
If theport = 421 Then portname = "Ariel"
If theport = 422 Then portname = "Ariel"
If theport = 423 Then portname = "IBM Operations Planning and Control Start"
If theport = 424 Then portname = "IBM Operations Planning and Control Track"
If theport = 425 Then portname = "ICAD"
If theport = 426 Then portname = "smartsdp"
If theport = 427 Then portname = "Server Location"
If theport = 428 Then portname = "OCS_CMU"
If theport = 429 Then portname = "OCS_AMU"
If theport = 430 Then portname = "UTMPSD"
If theport = 431 Then portname = "UTMPCD"
If theport = 432 Then portname = "IASD"
If theport = 433 Then portname = "NNSP"
If theport = 434 Then portname = "MobileIP-Agent"
If theport = 435 Then portname = "MobilIP-MN"
If theport = 436 Then portname = "DNA-CML"
If theport = 437 Then portname = "comscm"
If theport = 438 Then portname = "dsfgw"
If theport = 439 Then portname = "dasp      Thomas Obermair"
If theport = 440 Then portname = "sgcp"
If theport = 441 Then portname = "decvms-sysmgt"
If theport = 442 Then portname = "cvc_hostd"
If theport = 443 Then portname = "https  MCom"
If theport = 444 Then portname = "Simple Network Paging Protocol"
If theport = 445 Then portname = "Microsoft-DS"
If theport = 446 Then portname = "DDM-RDB"
If theport = 447 Then portname = "DDM-RFM"
If theport = 448 Then portname = "DDM-BYTE"
If theport = 449 Then portname = "AS Server Mapper"
If theport = 450 Then portname = "TServer"
If theport = 451 Then portname = "Cray Network Semaphore server"
If theport = 452 Then portname = "Cray SFS config server"
If theport = 453 Then portname = "CreativeServer"
If theport = 454 Then portname = "ContentServer"
If theport = 455 Then portname = "CreativePartnr"
If theport = 456 Then portname = "macon-tcp"
If theport = 457 Then portname = "scohelp"
If theport = 458 Then portname = "apple quick time"
If theport = 459 Then portname = "ampr-rcmd"
If theport = 460 Then portname = "skronk"
If theport = 461 Then portname = "DataRampSrv"
If theport = 462 Then portname = "DataRampSrvSec"
If theport = 463 Then portname = "alpes"
If theport = 464 Then portname = "kpasswd"
If theport = 465 Then portname = "ssmtp"
If theport = 466 Then portname = "digital-vrc"
If theport = 467 Then portname = "mylex-mapd"
If theport = 468 Then portname = "proturis"
If theport = 469 Then portname = "Radio Control Protocol"
If theport = 470 Then portname = "scx-proxy"
If theport = 471 Then portname = "Mondex"
If theport = 472 Then portname = "ljk-login"
If theport = 473 Then portname = "hybrid-pop"
If theport = 474 Then portname = "tn-tl-w1"
If theport = 475 Then portname = "tcpnethaspsrv"
If theport = 476 Then portname = "tn-tl-fd1"
If theport = 477 Then portname = "ss7ns"
If theport = 478 Then portname = "spsc"
If theport = 479 Then portname = "iafserver"
If theport = 480 Then portname = "iafdbase"
If theport = 481 Then portname = "Ph service"
If theport = 482 Then portname = "bgs-nsi"
If theport = 483 Then portname = "ulpnet"
If theport = 484 Then portname = "Integra Software Management Environment"
If theport = 485 Then portname = "Air Soft Power Burst"
If theport = 486 Then portname = "avian"
If theport = 487 Then portname = "saft"
If theport = 488 Then portname = "gss-http"
If theport = 489 Then portname = "nest-protocol"
If theport = 490 Then portname = "micom-pfs"
If theport = 491 Then portname = "go-login"
If theport = 492 Then portname = "Transport Independent Convergence for FNA"
If theport = 493 Then portname = "Transport Independent Convergence for FNA"
If theport = 494 Then portname = "POV-Ray"
If theport = 495 Then portname = "intecourier"
If theport = 496 Then portname = "PIM-RP-DISC"
If theport = 497 Then portname = "dantz"
If theport = 498 Then portname = "siam"
If theport = 499 Then portname = "ISO ILL Protocol"
If theport = 500 Then portname = "isakmp"
If theport = 501 Then portname = "STMF"
If theport = 502 Then portname = "asa-appl-proto"
If theport = 503 Then portname = "Intrinsa"
If theport = 504 Then portname = "citadel"
If theport = 505 Then portname = "mailbox-lm"
If theport = 506 Then portname = "ohimsrv"
If theport = 507 Then portname = "crs"
If theport = 508 Then portname = "xvttp"
If theport = 509 Then portname = "snare"
If theport = 510 Then portname = "FirstClass Protocol"
If theport = 511 Then portname = "mynet-as"
If theport = 512 Then portname = "remote process execution;"
If theport = 513 Then portname = "remote login a la telnet;"
If theport = 514 Then portname = "cmd"
If theport = 515 Then portname = "spooler"
If theport = 516 Then portname = "videotex"
If theport = 517 Then portname = "like tenex link"
If theport = 518 Then portname = "?"
If theport = 519 Then portname = "unixtime"
If theport = 520 Then portname = "extended file name server"
If theport = 521 Then portname = "ripng"
If theport = 522 Then portname = "ULP"
If theport = 523 Then portname = "IBM-DB2"
If theport = 524 Then portname = "NCP"
If theport = 525 Then portname = "timeserver"
If theport = 526 Then portname = "newdate"
If theport = 527 Then portname = "Stock IXChange"
If theport = 528 Then portname = "Customer IXChange"
If theport = 529 Then portname = "IRC-SERV"
If theport = 530 Then portname = "rpc"
If theport = 531 Then portname = "chat"
If theport = 532 Then portname = "readnews"
If theport = 533 Then portname = "for emergency broadcasts"
If theport = 534 Then portname = "MegaMedia Admin"
If theport = 535 Then portname = "iiop"
If theport = 536 Then portname = "opalis-rdv"
If theport = 537 Then portname = "Networked Media Streaming Protocol"
If theport = 538 Then portname = "gdomap"
If theport = 539 Then portname = "Apertus Technologies Load Determination"
If theport = 540 Then portname = "uucpd"
If theport = 541 Then portname = "uucp-rlogin"
If theport = 542 Then portname = "commerce"
If theport = 543 Then portname = "?"
If theport = 544 Then portname = "krcmd"
If theport = 545 Then portname = "appleqtcsrvr"
If theport = 546 Then portname = "DHCPv6 Client"
If theport = 547 Then portname = "DHCPv6 Server"
If theport = 548 Then portname = "AFP over TCP"
If theport = 549 Then portname = "IDFP"
If theport = 550 Then portname = "new-who"
If theport = 551 Then portname = "cybercash"
If theport = 552 Then portname = "deviceshare"
If theport = 553 Then portname = "pirp"
If theport = 554 Then portname = "Real Time Stream Control Protocol"
If theport = 555 Then portname = "?"
If theport = 556 Then portname = "rfs server"
If theport = 557 Then portname = "openvms-sysipc"
If theport = 558 Then portname = "SDNSKMP"
If theport = 559 Then portname = "TEEDTAP"
If theport = 560 Then portname = "rmonitord"
If theport = 561 Then portname = "?"
If theport = 562 Then portname = "chcmd"
If theport = 563 Then portname = "snews"
If theport = 564 Then portname = "plan 9 file service"
If theport = 565 Then portname = "whoami"
If theport = 566 Then portname = "streettalk"
If theport = 567 Then portname = "banyan-rpc"
If theport = 568 Then portname = "microsoft shuttle"
If theport = 569 Then portname = "microsoft rome"
If theport = 570 Then portname = "demon"
If theport = 571 Then portname = "udemon"
If theport = 572 Then portname = "sonar"
If theport = 573 Then portname = "banyan-vip"
If theport = 574 Then portname = "FTP Software Agent System"
If theport = 575 Then portname = "VEMMI"
If theport = 576 Then portname = "ipcd"
If theport = 577 Then portname = "vnas"
If theport = 578 Then portname = "ipdd"
If theport = 579 Then portname = "decbsrv"
If theport = 580 Then portname = "SNTP HEARTBEAT"
If theport = 581 Then portname = "Bundle Discovery Protocol"
If theport = 600 Then portname = "Sun IPC server"
If theport = 606 Then portname = "Cray Unified Resource Manager"
If theport = 607 Then portname = "nqs"
If theport = 608 Then portname = "Sender-Initiated/Unsolicited File Transfer"
If theport = 609 Then portname = "npmp-trap"
If theport = 610 Then portname = "npmp-local"
If theport = 611 Then portname = "npmp-gui"
If theport = 612 Then portname = "HMMP Indication"
If theport = 613 Then portname = "HMMP Operation"
If theport = 614 Then portname = "SSLshell"
If theport = 615 Then portname = "Internet Configuration Manager"
If theport = 616 Then portname = "SCO System Administration Server"
If theport = 617 Then portname = "SCO Desktop Administration Server"
If theport = 618 Then portname = "DEI-ICDA"
If theport = 619 Then portname = "Digital EVM"
If theport = 620 Then portname = "SCO WebServer Manager"
If theport = 633 Then portname = "Service Status update (Sterling Software)"
If theport = 634 Then portname = "ginad"
If theport = 635 Then portname = "RLZ DBase"
If theport = 636 Then portname = "ssl-ldap"
If theport = 637 Then portname = "lanserver"
If theport = 666 Then portname = "?"
If theport = 667 Then portname = "campaign contribution disclosures -  SDR Technologies"
If theport = 668 Then portname = "MeComm"
If theport = 669 Then portname = "MeRegister"
If theport = 670 Then portname = "VACDSM-SWS"
If theport = 671 Then portname = "VACDSM-APP"
If theport = 672 Then portname = "VPPS-QUA"
If theport = 673 Then portname = "CIMPLEX"
If theport = 674 Then portname = "ACAP"
If theport = 704 Then portname = "errlog copy/server daemon"
If theport = 705 Then portname = "AgentX"
If theport = 709 Then portname = "Entrust Key Management Service Handler"
If theport = 710 Then portname = "Entrust Administration Service Handler"
If theport = 729 Then portname = "IBM NetView DM/6000 Server/Client"
If theport = 730 Then portname = "IBM NetView DM/6000 send"
If theport = 731 Then portname = "IBM NetView DM/6000 receive"
If theport = 741 Then portname = "netGW"
If theport = 742 Then portname = "Network based Rev. Cont. Sys."
If theport = 744 Then portname = "Flexible License Manager"
If theport = 747 Then portname = "Fujitsu Device Control"
If theport = 748 Then portname = "Russell Info Sci Calendar Manager"
If theport = 749 Then portname = "kerberos administration"
If theport = 750 Then portname = "?"
If theport = 751 Then portname = "?"
If theport = 752 Then portname = "?"
If theport = 753 Then portname = "?"
If theport = 754 Then portname = "send"
If theport = 758 Then portname = "?"
If theport = 759 Then portname = "?"
If theport = 760 Then portname = "?"
If theport = 761 Then portname = "?"
If theport = 762 Then portname = "?"
If theport = 763 Then portname = "?"
If theport = 764 Then portname = "?"
If theport = 765 Then portname = "?"
If theport = 767 Then portname = "phone"
If theport = 769 Then portname = "?"
If theport = 770 Then portname = "?"
If theport = 771 Then portname = "?"
If theport = 772 Then portname = "?"
If theport = 773 Then portname = "?"
If theport = 774 Then portname = "?"
If theport = 775 Then portname = "?"
If theport = 776 Then portname = "?"
If theport = 780 Then portname = "?"
If theport = 786 Then portname = "Concert"
If theport = 800 Then portname = "?"
If theport = 801 Then portname = "?"
If theport = 886 Then portname = "ICL coNETion locate server"
If theport = 887 Then portname = "ICL coNETion server info"
If theport = 888 Then portname = "AccessBuilder"
If theport = 911 Then portname = "xact-backup"
If theport = 991 Then portname = "Netnews Administration System"
If theport = 995 Then portname = "SSL based POP3"
If theport = 996 Then portname = "vsinet"
If theport = 997 Then portname = "?"
If theport = 998 Then portname = "?"
If theport = 999 Then portname = "?"
If theport = 1000 Then portname = "?"
If theport = 1001 Then portname = "WEB ex trojan"
If theport = 1023 Then portname = "Reserved"
If theport = 1024 Then portname = "Reserved"
If theport = 1025 Then portname = "network blackjack"
If theport = 1027 Then portname = "ICQ?"
If theport = 1030 Then portname = "BBN IAD"
If theport = 1031 Then portname = "BBN IAD"
If theport = 1032 Then portname = "BBN IAD"
If theport = 1047 Then portname = "Sun's NEO Object Request Broker"
If theport = 1048 Then portname = "Sun's NEO Object Request Broker"
If theport = 1058 Then portname = "nim"
If theport = 1059 Then portname = "nimreg"
If theport = 1067 Then portname = "Installation Bootstrap Proto. Serv."
If theport = 1068 Then portname = "Installation Bootstrap Proto. Cli."
If theport = 1080 Then portname = "Socks"
If theport = 1083 Then portname = "Anasoft License Manager"
If theport = 1084 Then portname = "Anasoft License Manager"
If theport = 1089 Then portname = "SocksServer trojan"
If theport = 1110 Then portname = "Cluster status info"
If theport = 1123 Then portname = "Murray"
If theport = 1155 Then portname = "Network File Access"
If theport = 1212 Then portname = "lupa"
If theport = 1222 Then portname = "SNI R&D network"
If theport = 1248 Then portname = "?"
If theport = 1313 Then portname = "BMC_PATROLDB"
If theport = 1314 Then portname = "Photoscript Distributed Printing System"
If theport = 1345 Then portname = "VPJP"
If theport = 1346 Then portname = "Alta Analytics License Manager"
If theport = 1347 Then portname = "multi media conferencing"
If theport = 1348 Then portname = "multi media conferencing"
If theport = 1349 Then portname = "Registration Network Protocol"
If theport = 1350 Then portname = "Registration Network Protocol"
If theport = 1351 Then portname = "Digital Tool Works (MIT)"
If theport = 1352 Then portname = "Lotus Note"
If theport = 1353 Then portname = "Relief Consulting"
If theport = 1354 Then portname = "RightBrain Software"
If theport = 1355 Then portname = "Intuitive Edge"
If theport = 1356 Then portname = "CuillaMartin Company"
If theport = 1357 Then portname = "Electronic PegBoard"
If theport = 1358 Then portname = "CONNLCLI"
If theport = 1359 Then portname = "FTSRV"
If theport = 1360 Then portname = "MIMER"
If theport = 1361 Then portname = "LinX"
If theport = 1362 Then portname = "TimeFlies"
If theport = 1363 Then portname = "Network DataMover Requester"
If theport = 1364 Then portname = "Network DataMover Server"
If theport = 1365 Then portname = "Network Software Associates"
If theport = 1366 Then portname = "Novell NetWare Comm Service Platform"
If theport = 1367 Then portname = "DCS"
If theport = 1368 Then portname = "ScreenCast"
If theport = 1369 Then portname = "GlobalView to Unix Shell"
If theport = 1370 Then portname = "Unix Shell to GlobalView"
If theport = 1371 Then portname = "Fujitsu Config Protocol"
If theport = 1372 Then portname = "Fujitsu Config Protocol"
If theport = 1373 Then portname = "Chromagrafx"
If theport = 1374 Then portname = "EPI Software Systems"
If theport = 1375 Then portname = "Bytex"
If theport = 1376 Then portname = "IBM Person to Person Software"
If theport = 1377 Then portname = "Cichlid License Manager"
If theport = 1378 Then portname = "Elan License Manager"
If theport = 1379 Then portname = "Integrity Solutions"
If theport = 1380 Then portname = "Telesis Network License Manager"
If theport = 1381 Then portname = "Apple Network License Manager"
If theport = 1382 Then portname = "?"
If theport = 1383 Then portname = "GW Hannaway Network License Manager"
If theport = 1384 Then portname = "Objective Solutions License Manager"
If theport = 1385 Then portname = "Atex Publishing License Manager"
If theport = 1386 Then portname = "CheckSum License Manager"
If theport = 1387 Then portname = "Computer Aided Design Software Inc LM"
If theport = 1388 Then portname = "Objective Solutions DataBase Cache"
If theport = 1389 Then portname = "Document Manager"
If theport = 1390 Then portname = "Storage Controller"
If theport = 1391 Then portname = "Storage Access Server"
If theport = 1392 Then portname = "Print Manager"
If theport = 1393 Then portname = "Network Log Server"
If theport = 1394 Then portname = "Network Log Client"
If theport = 1395 Then portname = "PC Workstation Manager software"
If theport = 1396 Then portname = "DVL Active Mail"
If theport = 1397 Then portname = "Audio Active Mail"
If theport = 1398 Then portname = "Video Active Mail"
If theport = 1399 Then portname = "Cadkey License Manager"
If theport = 1400 Then portname = "Cadkey Tablet Daemon"
If theport = 1401 Then portname = "Goldleaf License Manager"
If theport = 1402 Then portname = "Prospero Resource Manager"
If theport = 1403 Then portname = "Prospero Resource Manager"
If theport = 1404 Then portname = "Infinite Graphics License Manager"
If theport = 1405 Then portname = "IBM Remote Execution Starter"
If theport = 1406 Then portname = "NetLabs License Manager"
If theport = 1407 Then portname = "DBSA License Manager"
If theport = 1408 Then portname = "Sophia License Manager"
If theport = 1409 Then portname = "Here License Manager"
If theport = 1410 Then portname = "HiQ License Manager"
If theport = 1411 Then portname = "AudioFile"
If theport = 1412 Then portname = "InnoSys"
If theport = 1413 Then portname = "Innosys-ACL"
If theport = 1414 Then portname = "IBM MQSeries"
If theport = 1415 Then portname = "DBStar"
If theport = 1416 Then portname = "Novell LU6.2"
If theport = 1417 Then portname = "Timbuktu Service 1 Port"
If theport = 1418 Then portname = "Timbuktu Service 2 Port"
If theport = 1419 Then portname = "Timbuktu Service 3 Port"
If theport = 1420 Then portname = "Timbuktu Service 4 Port"
If theport = 1421 Then portname = "Gandalf License Manager"
If theport = 1422 Then portname = "Autodesk License Manager"
If theport = 1423 Then portname = "Essbase Arbor Software"
If theport = 1424 Then portname = "Hybrid Encryption Protocol"
If theport = 1425 Then portname = "Zion Software License Manager"
If theport = 1426 Then portname = "Satellite-data Acquisition System 1"
If theport = 1427 Then portname = "mloadd monitoring tool"
If theport = 1428 Then portname = "Informatik License Manager"
If theport = 1429 Then portname = "Hypercom NMS"
If theport = 1430 Then portname = "Hypercom TPDU"
If theport = 1431 Then portname = "Reverse Gossip Transport"
If theport = 1432 Then portname = "Blueberry Software License Manager"
If theport = 1433 Then portname = "Microsoft-SQL-Server"
If theport = 1434 Then portname = "Microsoft-SQL-Monitor"
If theport = 1435 Then portname = "IBM CICS"
If theport = 1436 Then portname = "Satellite-data Acquisition System 2"
If theport = 1437 Then portname = "Tabula"
If theport = 1438 Then portname = "Eicon Security Agent/Server"
If theport = 1439 Then portname = "Eicon X25/SNA Gateway"
If theport = 1440 Then portname = "Eicon Service Location Protocol"
If theport = 1441 Then portname = "Cadis License Management"
If theport = 1442 Then portname = "Cadis License Management"
If theport = 1443 Then portname = "Integrated Engineering Software"
If theport = 1444 Then portname = "Marcam  License Management"
If theport = 1445 Then portname = "Proxima License Manager"
If theport = 1446 Then portname = "Optical Research Associates License Manager"
If theport = 1447 Then portname = "Applied Parallel Research LM"
If theport = 1448 Then portname = "OpenConnect License Manager"
If theport = 1449 Then portname = "PEport"
If theport = 1450 Then portname = "Tandem Distributed Workbench Facility"
If theport = 1451 Then portname = "IBM Information Management"
If theport = 1452 Then portname = "GTE Government Systems License Man"
If theport = 1453 Then portname = "Genie License Manager"
If theport = 1454 Then portname = "interHDL License Manager"
If theport = 1455 Then portname = "ESL License Manager"
If theport = 1456 Then portname = "DCA"
If theport = 1457 Then portname = "Valisys License Manager"
If theport = 1458 Then portname = "Nichols Research Corp."
If theport = 1459 Then portname = "Proshare Notebook Application"
If theport = 1460 Then portname = "Proshare Notebook Application"
If theport = 1461 Then portname = "IBM Wireless LAN"
If theport = 1462 Then portname = "World License Manager"
If theport = 1463 Then portname = "Nucleus"
If theport = 1464 Then portname = "MSL License Manager"
If theport = 1465 Then portname = "Pipes Platform"
If theport = 1466 Then portname = "Ocean Software License Manager"
If theport = 1467 Then portname = "CSDMBASE"
If theport = 1468 Then portname = "CSDM"
If theport = 1469 Then portname = "Active Analysis Limited License Manager"
If theport = 1470 Then portname = "Universal Analytics"
If theport = 1471 Then portname = "csdmbase"
If theport = 1472 Then portname = "csdm"
If theport = 1473 Then portname = "OpenMath"
If theport = 1474 Then portname = "Telefinder"
If theport = 1475 Then portname = "Taligent License Manager"
If theport = 1476 Then portname = "clvm-cfg"
If theport = 1477 Then portname = "ms-sna-server"
If theport = 1478 Then portname = "ms-sna-base"
If theport = 1479 Then portname = "dberegister"
If theport = 1480 Then portname = "PacerForum"
If theport = 1481 Then portname = "AIRS"
If theport = 1482 Then portname = "Miteksys License Manager"
If theport = 1483 Then portname = "AFS License Manager"
If theport = 1484 Then portname = "Confluent License Manager"
If theport = 1485 Then portname = "LANSource"
If theport = 1486 Then portname = "nms_topo_serv"
If theport = 1487 Then portname = "LocalInfoSrvr"
If theport = 1488 Then portname = "DocStor"
If theport = 1489 Then portname = "dmdocbroker"
If theport = 1490 Then portname = "insitu-conf"
If theport = 1491 Then portname = "anynetgateway"
If theport = 1492 Then portname = "stone-design-1"
If theport = 1493 Then portname = "netmap_lm"
If theport = 1494 Then portname = "ica"
If theport = 1495 Then portname = "cvc"
If theport = 1496 Then portname = "liberty-lm"
If theport = 1497 Then portname = "rfx-lm"
If theport = 1498 Then portname = "Watcom-SQL"
If theport = 1499 Then portname = "Federico Heinz Consultora"
If theport = 1500 Then portname = "VLSI License Manager"
If theport = 1501 Then portname = "Satellite-data Acquisition System 3"
If theport = 1502 Then portname = "Shiva"
If theport = 1503 Then portname = "Databeam"
If theport = 1504 Then portname = "EVB Software Engineering License Manager"
If theport = 1505 Then portname = "Funk Software"
If theport = 1506 Then portname = "Universal Time daemon (utcd)"
If theport = 1507 Then portname = "symplex"
If theport = 1508 Then portname = "diagmond"
If theport = 1509 Then portname = "Robcad"
If theport = 1510 Then portname = "Midland Valley Exploration Ltd. Lic. Man."
If theport = 1511 Then portname = "3l-l1"
If theport = 1512 Then portname = "Microsoft's Windows Internet Name Service"
If theport = 1513 Then portname = "Fujitsu Systems Business of America"
If theport = 1514 Then portname = "Fujitsu Systems Business of America"
If theport = 1515 Then portname = "ifor-protocol"
If theport = 1516 Then portname = "Virtual Places Audio data"
If theport = 1517 Then portname = "Virtual Places Audio control"
If theport = 1518 Then portname = "Virtual Places Video data"
If theport = 1519 Then portname = "Virtual Places Video control"
If theport = 1520 Then portname = "atm zip office"
If theport = 1521 Then portname = "nCube License Manager"
If theport = 1522 Then portname = "Ricardo North America License Manager"
If theport = 1523 Then portname = "cichild"
If theport = 1524 Then portname = "ingres"
If theport = 1525 Then portname = "oracle"
If theport = 1526 Then portname = "Prospero Data Access Prot non-priv"
If theport = 1527 Then portname = "oracle"
If theport = 1528 Then portname = "micautoreg"
If theport = 1529 Then portname = "oracle"
If theport = 1530 Then portname = "rap-service"
If theport = 1531 Then portname = "rap-listen"
If theport = 1532 Then portname = "miroconnect"
If theport = 1533 Then portname = "Virtual Places Software"
If theport = 1534 Then portname = "micromuse-lm"
If theport = 1535 Then portname = "ampr-info"
If theport = 1536 Then portname = "ampr-inter"
If theport = 1537 Then portname = "isi-lm"
If theport = 1538 Then portname = "3ds-lm"
If theport = 1539 Then portname = "Intellistor License Manager"
If theport = 1540 Then portname = "rds"
If theport = 1541 Then portname = "rds2"
If theport = 1542 Then portname = "gridgen-elmd"
If theport = 1543 Then portname = "simba-cs"
If theport = 1544 Then portname = "aspeclmd"
If theport = 1545 Then portname = "vistium-share"
If theport = 1546 Then portname = "abbaccuray"
If theport = 1547 Then portname = "laplink"
If theport = 1548 Then portname = "Axon License Manager"
If theport = 1549 Then portname = "Shiva Hose"
If theport = 1550 Then portname = "Image Storage license manager 3M Company"
If theport = 1551 Then portname = "HECMTL-DB"
If theport = 1552 Then portname = "pciarray"
If theport = 1553 Then portname = "sna-cs"
If theport = 1554 Then portname = "CACI Products Company License Manager"
If theport = 1555 Then portname = "livelan"
If theport = 1556 Then portname = "AshWin CI Tecnologies"
If theport = 1557 Then portname = "ArborText License Manager"
If theport = 1558 Then portname = "xingmpeg"
If theport = 1559 Then portname = "web2host"
If theport = 1560 Then portname = "asci-val"
If theport = 1561 Then portname = "facilityview"
If theport = 1562 Then portname = "pconnectmgr"
If theport = 1563 Then portname = "Cadabra License Manager"
If theport = 1564 Then portname = "Pay-Per-View"
If theport = 1565 Then portname = "WinDD"
If theport = 1566 Then portname = "CORELVIDEO"
If theport = 1567 Then portname = "jlicelmd"
If theport = 1568 Then portname = "tsspmap"
If theport = 1569 Then portname = "ets"
If theport = 1570 Then portname = "orbixd"
If theport = 1571 Then portname = "Oracle Remote Data Base"
If theport = 1572 Then portname = "Chipcom License Manager"
If theport = 1573 Then portname = "itscomm-ns"
If theport = 1574 Then portname = "mvel-lm"
If theport = 1575 Then portname = "oraclenames"
If theport = 1576 Then portname = "moldflow-lm"
If theport = 1577 Then portname = "hypercube-lm"
If theport = 1578 Then portname = "Jacobus License Manager"
If theport = 1579 Then portname = "ioc-sea-lm"
If theport = 1580 Then portname = "tn-tl-r1"
If theport = 1581 Then portname = "vmf-msg-port"
If theport = 1582 Then portname = "MSIMS"
If theport = 1583 Then portname = "simbaexpress"
If theport = 1584 Then portname = "tn-tl-fd2"
If theport = 1585 Then portname = "intv"
If theport = 1586 Then portname = "ibm-abtact"
If theport = 1587 Then portname = "pra_elmd"
If theport = 1588 Then portname = "triquest-lm"
If theport = 1589 Then portname = "VQP"
If theport = 1590 Then portname = "gemini-lm"
If theport = 1591 Then portname = "ncpm-pm"
If theport = 1592 Then portname = "commonspace"
If theport = 1593 Then portname = "mainsoft-lm"
If theport = 1594 Then portname = "sixtrak"
If theport = 1595 Then portname = "radio"
If theport = 1596 Then portname = "radio-sm"
If theport = 1597 Then portname = "orbplus-iiop"
If theport = 1598 Then portname = "picknfs"
If theport = 1599 Then portname = "simbaservices"
If theport = 1600 Then portname = "?"
If theport = 1601 Then portname = "aas"
If theport = 1602 Then portname = "inspect"
If theport = 1603 Then portname = "pickodbc"
If theport = 1604 Then portname = "icabrowser"
If theport = 1605 Then portname = "Salutation Manager (Salutation Protocol)"
If theport = 1606 Then portname = "Salutation Manager (SLM-API)"
If theport = 1607 Then portname = "stt"
If theport = 1608 Then portname = "Smart Corp. License Manager"
If theport = 1609 Then portname = "isysg-lm"
If theport = 1610 Then portname = "taurus-wh"
If theport = 1611 Then portname = "Inter Library Loan"
If theport = 1612 Then portname = "NetBill Transaction Server"
If theport = 1613 Then portname = "NetBill Key Repository"
If theport = 1614 Then portname = "NetBill Credential Server"
If theport = 1615 Then portname = "NetBill Authorization Server"
If theport = 1616 Then portname = "NetBill Product Server"
If theport = 1617 Then portname = "Nimrod Inter-Agent Communication"
If theport = 1618 Then portname = "skytelnet"
If theport = 1619 Then portname = "xs-openstorage"
If theport = 1620 Then portname = "faxportwinport"
If theport = 1621 Then portname = "softdataphone"
If theport = 1622 Then portname = "ontime"
If theport = 1623 Then portname = "jaleosnd"
If theport = 1624 Then portname = "udp-sr-port"
If theport = 1625 Then portname = "svs-omagent"
If theport = 1636 Then portname = "CableNet Control Protocol"
If theport = 1637 Then portname = "CableNet Admin Protocol"
If theport = 1638 Then portname = "CableNet Info Protocol"
If theport = 1639 Then portname = "cert-initiator"
If theport = 1640 Then portname = "cert-responder"
If theport = 1641 Then portname = "InVision"
If theport = 1642 Then portname = "isis-am"
If theport = 1643 Then portname = "isis-ambc"
If theport = 1644 Then portname = "Satellite-data Acquisition System 4"
If theport = 1645 Then portname = "datametrics"
If theport = 1646 Then portname = "sa-msg-port"
If theport = 1647 Then portname = "rsap"
If theport = 1648 Then portname = "concurrent-lm"
If theport = 1649 Then portname = "inspect"
If theport = 1650 Then portname = "?"
If theport = 1651 Then portname = "shiva_confsrvr"
If theport = 1652 Then portname = "xnmp"
If theport = 1653 Then portname = "alphatech-lm"
If theport = 1654 Then portname = "stargatealerts"
If theport = 1655 Then portname = "dec-mbadmin"
If theport = 1656 Then portname = "dec-mbadmin-h"
If theport = 1657 Then portname = "fujitsu-mmpdc"
If theport = 1658 Then portname = "sixnetudr"
If theport = 1659 Then portname = "Silicon Grail License Manager"
If theport = 1660 Then portname = "skip-mc-gikreq"
If theport = 1661 Then portname = "netview-aix-1"
If theport = 1662 Then portname = "netview-aix-2"
If theport = 1663 Then portname = "netview-aix-3"
If theport = 1664 Then portname = "netview-aix-4"
If theport = 1665 Then portname = "netview-aix-5"
If theport = 1666 Then portname = "netview-aix-6"
If theport = 1667 Then portname = "netview-aix-7"
If theport = 1668 Then portname = "netview-aix-8"
If theport = 1669 Then portname = "netview-aix-9"
If theport = 1670 Then portname = "netview-aix-10"
If theport = 1671 Then portname = "netview-aix-11"
If theport = 1672 Then portname = "netview-aix-12"
If theport = 1673 Then portname = "Intel Proshare Multicast"
If theport = 1674 Then portname = "Intel Proshare Multicast"
If theport = 1675 Then portname = "Pacific Data Products"
If theport = 1676 Then portname = "netcomm1"
If theport = 1677 Then portname = "groupwise"
If theport = 1678 Then portname = "prolink"
If theport = 1679 Then portname = "darcorp-lm"
If theport = 1680 Then portname = "microcom-sbp"
If theport = 1681 Then portname = "sd-elmd"
If theport = 1682 Then portname = "lanyon-lantern"
If theport = 1683 Then portname = "ncpm-hip"
If theport = 1684 Then portname = "SnareSecure"
If theport = 1685 Then portname = "n2nremote"
If theport = 1686 Then portname = "cvmon"
If theport = 1687 Then portname = "nsjtp-ctrl"
If theport = 1688 Then portname = "nsjtp-data"
If theport = 1689 Then portname = "firefox"
If theport = 1690 Then portname = "ng-umds"
If theport = 1691 Then portname = "empire-empuma"
If theport = 1692 Then portname = "sstsys-lm"
If theport = 1693 Then portname = "rrirtr"
If theport = 1694 Then portname = "rrimwm"
If theport = 1695 Then portname = "rrilwm"
If theport = 1696 Then portname = "rrifmm"
If theport = 1697 Then portname = "rrisat"
If theport = 1698 Then portname = "RSVP-ENCAPSULATION-1"
If theport = 1699 Then portname = "RSVP-ENCAPSULATION-2"
If theport = 1700 Then portname = "mps-raft"
If theport = 1701 Then portname = "l2f"
If theport = 1702 Then portname = "deskshare"
If theport = 1703 Then portname = "hb-engine"
If theport = 1704 Then portname = "bcs-broker"
If theport = 1705 Then portname = "slingshot"
If theport = 1706 Then portname = "jetform"
If theport = 1707 Then portname = "vdmplay"
If theport = 1708 Then portname = "gat-lmd"
If theport = 1709 Then portname = "centra"
If theport = 1710 Then portname = "impera"
If theport = 1711 Then portname = "pptconference"
If theport = 1712 Then portname = "resource monitoring service"
If theport = 1713 Then portname = "ConferenceTalk"
If theport = 1714 Then portname = "sesi-lm"
If theport = 1715 Then portname = "houdini-lm"
If theport = 1716 Then portname = "xmsg"
If theport = 1717 Then portname = "fj-hdnet"
If theport = 1718 Then portname = "h323gatedisc"
If theport = 1719 Then portname = "h323gatestat"
If theport = 1720 Then portname = "h323hostcall"
If theport = 1721 Then portname = "caicci"
If theport = 1722 Then portname = "HKS License Manager"
If theport = 1723 Then portname = "pptp"
If theport = 1724 Then portname = "csbphonemaster"
If theport = 1725 Then portname = "iden-ralp"
If theport = 1726 Then portname = "IBERIAGAMES"
If theport = 1727 Then portname = "winddx"
If theport = 1728 Then portname = "TELINDUS"
If theport = 1729 Then portname = "CityNL License Management"
If theport = 1730 Then portname = "roketz"
If theport = 1731 Then portname = "MSICCP"
If theport = 1732 Then portname = "proxim"
If theport = 1733 Then portname = "sipat"
If theport = 1734 Then portname = "Camber Corporation License Management"
If theport = 1735 Then portname = "PrivateChat"
If theport = 1736 Then portname = "street-stream"
If theport = 1737 Then portname = "ultimad"
If theport = 1738 Then portname = "GameGen1"
If theport = 1739 Then portname = "webaccess"
If theport = 1740 Then portname = "encore"
If theport = 1741 Then portname = "cisco-net-mgmt"
If theport = 1742 Then portname = "3Com-nsd"
If theport = 1743 Then portname = "Cinema Graphics License Manager"
If theport = 1744 Then portname = "ncpm-ft"
If theport = 1745 Then portname = "remote-winsock"
If theport = 1746 Then portname = "ftrapid-1"
If theport = 1747 Then portname = "ftrapid-2"
If theport = 1748 Then portname = "oracle-em1"
If theport = 1749 Then portname = "aspen-services"
If theport = 1750 Then portname = "Simple Socket Library's PortMaster"
If theport = 1751 Then portname = "SwiftNet"
If theport = 1752 Then portname = "Leap of Faith Research License Manager"
If theport = 1753 Then portname = "Translogic License Manager"
If theport = 1754 Then portname = "oracle-em2"
If theport = 1755 Then portname = "ms-streaming"
If theport = 1756 Then portname = "capfast-lmd"
If theport = 1757 Then portname = "cnhrp"
If theport = 1758 Then portname = "tftp-mcast"
If theport = 1759 Then portname = "SPSS License Manager"
If theport = 1760 Then portname = "www-ldap-gw"
If theport = 1761 Then portname = "cft-0"
If theport = 1762 Then portname = "cft-1"
If theport = 1763 Then portname = "cft-2"
If theport = 1764 Then portname = "cft-3"
If theport = 1765 Then portname = "cft-4"
If theport = 1766 Then portname = "cft-5"
If theport = 1767 Then portname = "cft-6"
If theport = 1768 Then portname = "cft-7"
If theport = 1769 Then portname = "bmc-net-adm"
If theport = 1770 Then portname = "bmc-net-svc"
If theport = 1771 Then portname = "vaultbase"
If theport = 1772 Then portname = "EssWeb Gateway"
If theport = 1773 Then portname = "KMSControl"
If theport = 1774 Then portname = "global-dtserv"
If theport = 1776 Then portname = "Federal Emergency Management Information System"
If theport = 1777 Then portname = "powerguardian"
If theport = 1778 Then portname = "prodigy-internet"
If theport = 1779 Then portname = "pharmasoft"
If theport = 1780 Then portname = "dpkeyserv"
If theport = 1781 Then portname = "answersoft-lm"
If theport = 1782 Then portname = "hp-hcip"
If theport = 1783 Then portname = "Fujitsu Remote Install Service"
If theport = 1784 Then portname = "Finle License Manager"
If theport = 1785 Then portname = "Wind River Systems License Manager"
If theport = 1786 Then portname = "funk-logger"
If theport = 1787 Then portname = "funk-license"
If theport = 1788 Then portname = "psmond"
If theport = 1789 Then portname = "hello"
If theport = 1790 Then portname = "Narrative Media Streaming Protocol"
If theport = 1791 Then portname = "EA1"
If theport = 1792 Then portname = "ibm-dt-2"
If theport = 1793 Then portname = "rsc-robot"
If theport = 1794 Then portname = "cera-bcm"
If theport = 1795 Then portname = "dpi-proxy"
If theport = 1796 Then portname = "Vocaltec Server Administration"
If theport = 1797 Then portname = "UMA"
If theport = 1798 Then portname = "Event Transfer Protocol"
If theport = 1799 Then portname = "NETRISK"
If theport = 1800 Then portname = "ANSYS-License manager"
If theport = 1801 Then portname = "Microsoft Message Que"
If theport = 1802 Then portname = "ConComp1"
If theport = 1803 Then portname = "HP-HCIP-GWY"
If theport = 1804 Then portname = "ENL"
If theport = 1805 Then portname = "ENL-Name"
If theport = 1806 Then portname = "Musiconline"
If theport = 1807 Then portname = "Fujitsu Hot Standby Protocol"
If theport = 1808 Then portname = "Oracle-VP2"
If theport = 1809 Then portname = "Oracle-VP1"
If theport = 1810 Then portname = "Jerand License Manager"
If theport = 1811 Then portname = "Scientia-SDB"
If theport = 1812 Then portname = "RADIUS"
If theport = 1813 Then portname = "RADIUS Accounting"
If theport = 1814 Then portname = "TDP Suite"
If theport = 1815 Then portname = "MMPFT"
If theport = 1818 Then portname = "Enhanced Trivial File Transfer Protocol"
If theport = 1819 Then portname = "Plato License Manager"
If theport = 1820 Then portname = "mcagent"
If theport = 1821 Then portname = "donnyworld"
If theport = 1822 Then portname = "es-elmd"
If theport = 1823 Then portname = "Unisys Natural Language License Manager"
If theport = 1824 Then portname = "metrics-pas"
If theport = 1901 Then portname = "Fujitsu ICL Terminal Emulator Program A"
If theport = 1902 Then portname = "Fujitsu ICL Terminal Emulator Program B"
If theport = 1903 Then portname = "Local Link Name Resolution"
If theport = 1904 Then portname = "Fujitsu ICL Terminal Emulator Program C"
If theport = 1905 Then portname = "Secure UP.Link Gateway Protocol"
If theport = 1906 Then portname = "TPortMapperReq"
If theport = 1907 Then portname = "IntraSTAR"
If theport = 1908 Then portname = "Dawn"
If theport = 1909 Then portname = "Global World Link"
If theport = 1911 Then portname = "Starlight Networks Multimedia Transport Protocol"
If theport = 1912 Then portname = "Unassigned"
If theport = 1913 Then portname = "armadp"
If theport = 1914 Then portname = "Elm-Momentum"
If theport = 1915 Then portname = "FACELINK"
If theport = 1916 Then portname = "Persoft Persona"
If theport = 1917 Then portname = "nOAgent"
If theport = 1918 Then portname = "Candle Directory Service - NDS"
If theport = 1919 Then portname = "Candle Directory Service - DCH"
If theport = 1920 Then portname = "Candle Directory Service - FERRET"
If theport = 1944 Then portname = "close-combat"
If theport = 1945 Then portname = "dialogic-elmd"
If theport = 1946 Then portname = "tekpls"
If theport = 1947 Then portname = "hlserver"
If theport = 1948 Then portname = "eye2eye"
If theport = 1949 Then portname = "ISMA Easdaq Live"
If theport = 1950 Then portname = "ISMA Easdaq Test"
If theport = 1951 Then portname = "bcs-lmserver"
If theport = 1973 Then portname = "Data Link Switching Remote Access Protocol"
If theport = 1985 Then portname = "Folio Remote Server"
If theport = 1986 Then portname = "cisco license management"
If theport = 1987 Then portname = "cisco RSRB Priority 1 port"
If theport = 1988 Then portname = "cisco RSRB Priority 2 port"
If theport = 1989 Then portname = "cisco RSRB Priority 3 port"
If theport = 1990 Then portname = "cisco STUN Priority 1 port"
If theport = 1991 Then portname = "cisco STUN Priority 2 port"
If theport = 1992 Then portname = "cisco STUN Priority 3 port"
If theport = 1993 Then portname = "cisco SNMP TCP port"
If theport = 1994 Then portname = "cisco serial tunnel port"
If theport = 1995 Then portname = "cisco perf port"
If theport = 1996 Then portname = "cisco Remote SRB port"
If theport = 1997 Then portname = "cisco Gateway Discovery Protocol"
If theport = 1998 Then portname = "cisco X.25 service (XOT)"
If theport = 1999 Then portname = "cisco identification port"
If theport = 2000 Then portname = "?"
If theport = 2001 Then portname = "?"
If theport = 2002 Then portname = "?"
If theport = 2004 Then portname = "?"
If theport = 2005 Then portname = "?"
If theport = 2006 Then portname = "?"
If theport = 2007 Then portname = "?"
If theport = 2008 Then portname = "?"
If theport = 2009 Then portname = "n"
If theport = 2010 Then portname = "?"
If theport = 2011 Then portname = "raid"
If theport = 2012 Then portname = "?"
If theport = 2013 Then portname = "?"
If theport = 2014 Then portname = "?"
If theport = 2015 Then portname = "?"
If theport = 2016 Then portname = "?"
If theport = 2017 Then portname = "?"
If theport = 2018 Then portname = "?"
If theport = 2019 Then portname = "?"
If theport = 2020 Then portname = "?"
If theport = 2021 Then portname = "?"
If theport = 2022 Then portname = "?"
If theport = 2023 Then portname = "?"
If theport = 2024 Then portname = "?"
If theport = 2025 Then portname = "?"
If theport = 2026 Then portname = "?"
If theport = 2027 Then portname = "?"
If theport = 2028 Then portname = "?"
If theport = 2030 Then portname = "?"
If theport = 2032 Then portname = "?"
If theport = 2033 Then portname = "?"
If theport = 2034 Then portname = "?"
If theport = 2035 Then portname = "?"
If theport = 2038 Then portname = "?"
If theport = 2040 Then portname = "?"
If theport = 2041 Then portname = "?"
If theport = 2042 Then portname = "isis"
If theport = 2043 Then portname = "isis-bcast"
If theport = 2044 Then portname = "?"
If theport = 2045 Then portname = "?"
If theport = 2046 Then portname = "?"
If theport = 2047 Then portname = "?"
If theport = 2048 Then portname = "?"
If theport = 2049 Then portname = "?"
If theport = 2065 Then portname = "Data Link Switch Read Port Number"
If theport = 2067 Then portname = "Data Link Switch Write Port Number"
If theport = 2102 Then portname = "Zephyr server"
If theport = 2103 Then portname = "Zephyr serv-hm connection"
If theport = 2104 Then portname = "Zephyr hostmanager"
If theport = 2105 Then portname = "MiniPay"
If theport = 2201 Then portname = "Advanced Training System Program"
If theport = 2202 Then portname = "Int. Multimedia Teleconferencing Cosortium"
If theport = 2213 Then portname = "Kali"
If theport = 2221 Then portname = "Allen-Bradley unregistered port"
If theport = 2222 Then portname = "Allen-Bradley unregistered port"
If theport = 2223 Then portname = "Allen-Bradley unregistered port"
If theport = 2232 Then portname = "IVS Video default"
If theport = 2233 Then portname = "INFOCRYPT"
If theport = 2234 Then portname = "DirectPlay"
If theport = 2235 Then portname = "Sercomm-WLink"
If theport = 2236 Then portname = "Nani"
If theport = 2237 Then portname = "Optech Port1 License Manager"
If theport = 2238 Then portname = "AVIVA SNA SERVER"
If theport = 2239 Then portname = "Image Query"
If theport = 2241 Then portname = "IVS Daemon"
If theport = 2279 Then portname = "xmquery"
If theport = 2280 Then portname = "LNVPOLLER"
If theport = 2281 Then portname = "LNVCONSOLE"
If theport = 2282 Then portname = "LNVALARM"
If theport = 2283 Then portname = "LNVSTATUS"
If theport = 2284 Then portname = "LNVMAPS"
If theport = 2285 Then portname = "LNVMAILMON"
If theport = 2286 Then portname = "NAS-Metering"
If theport = 2287 Then portname = "DNA"
If theport = 2288 Then portname = "NETML"
If theport = 2301 Then portname = "Compaq Insight Manager"
If theport = 2307 Then portname = "pehelp"
If theport = 2401 Then portname = "cvspserver"
If theport = 2500 Then portname = "Resource Tracking system server"
If theport = 2501 Then portname = "Resource Tracking system client"
If theport = 2564 Then portname = "HP 3000 NS/VT block mode telnet"
If theport = 2583 Then portname = "Wincrash V2.0 trojan"
If theport = 2592 Then portname = "netrek"
If theport = 2700 Then portname = "tqdata"
If theport = 2784 Then portname = "world wide web - development"
If theport = 2785 Then portname = "aic-np"
If theport = 2786 Then portname = "aic-oncrpc - Destiny MCD database"
If theport = 2787 Then portname = "piccolo - Cornerstone Software"
If theport = 2788 Then portname = "NetWare Loadable Module - Seagate Software"
If theport = 2789 Then portname = "Media Agent"
If theport = 2801 Then portname = "Phineas trojan"
If theport = 2908 Then portname = "mao"
If theport = 2909 Then portname = "Funk Dialout"
If theport = 2910 Then portname = "TDAccess"
If theport = 2911 Then portname = "Blockade"
If theport = 2912 Then portname = "Epicon"
If theport = 3000 Then portname = "HBCI"
If theport = 3001 Then portname = "Redwood Broker"
If theport = 3002 Then portname = "EXLM Agent"
If theport = 3010 Then portname = "Telerate Workstation"
If theport = 3011 Then portname = "Trusted Web"
If theport = 3047 Then portname = "Fast Security HL Server"
If theport = 3048 Then portname = "Sierra Net PC Trader"
If theport = 3049 Then portname = "?"
If theport = 3128 Then portname = "Squid Proxy"
If theport = 3141 Then portname = "VMODEM"
If theport = 3142 Then portname = "RDC WH EOS"
If theport = 3143 Then portname = "Sea View"
If theport = 3144 Then portname = "Tarantella"
If theport = 3145 Then portname = "CSI-LFAP"
If theport = 3264 Then portname = "cc:mail/lotus"
If theport = 3333 Then portname = "DEC Notes"
If theport = 3421 Then portname = "Bull Apprise portmapper"
If theport = 3454 Then portname = "Apple Remote Access Protocol"
If theport = 3455 Then portname = "RSVP Port"
If theport = 3456 Then portname = "VAT default data"
If theport = 3457 Then portname = "VAT default control"
If theport = 3883 Then portname = "Deep Throat 2 trojan"
If theport = 3900 Then portname = "Unidata UDT OS"
If theport = 3984 Then portname = "MAPPER network node manager"
If theport = 3985 Then portname = "MAPPER TCP/IP server"
If theport = 3986 Then portname = "MAPPER workstation server"
If theport = 4008 Then portname = "NetCheque accounting"
If theport = 4009 Then portname = "Chimera HWM"
If theport = 4132 Then portname = "NUTS Daemon"
If theport = 4133 Then portname = "NUTS Bootp Server"
If theport = 4134 Then portname = "NIFTY-Serve HMI protocol"
If theport = 4321 Then portname = "Remote Who Is"
If theport = 4343 Then portname = "UNICALL"
If theport = 4444 Then portname = "KRB524"
If theport = 4445 Then portname = "UPNOTIFYP"
If theport = 4446 Then portname = "N1-FWP"
If theport = 4447 Then portname = "N1-RMGMT"
If theport = 4448 Then portname = "ASC Licence Manager"
If theport = 4449 Then portname = "ARCrypto IP"
If theport = 4450 Then portname = "Camp"
If theport = 4451 Then portname = "CTI System Msg"
If theport = 4452 Then portname = "CTI Program Load"
If theport = 4453 Then portname = "NSS Alert Manager"
If theport = 4454 Then portname = "NSS Agent Manager"
If theport = 4500 Then portname = "sae-urn"
If theport = 4501 Then portname = "urn-x-cdchoice"
If theport = 4672 Then portname = "remote file access server"
If theport = 5000 Then portname = "?"
If theport = 5001 Then portname = "?"
If theport = 5002 Then portname = "radio free ethernet"
If theport = 5003 Then portname = "Claris FileMaker Pro"
If theport = 5004 Then portname = "avt-profile-1"
If theport = 5005 Then portname = "avt-profile-2"
If theport = 5010 Then portname = "TelepathStart"
If theport = 5011 Then portname = "TelepathAttack"
If theport = 5020 Then portname = "zenginkyo-1"
If theport = 5021 Then portname = "zenginkyo-2"
If theport = 5050 Then portname = "multimedia conference control tool"
If theport = 5145 Then portname = "?"
If theport = 5150 Then portname = "Ascend Tunnel Management Protocol"
If theport = 5190 Then portname = "America-Online"
If theport = 5191 Then portname = "AmericaOnline1"
If theport = 5192 Then portname = "AmericaOnline2"
If theport = 5193 Then portname = "AmericaOnline3"
If theport = 5236 Then portname = "?"
If theport = 5300 Then portname = "# HA cluster heartbeat"
If theport = 5301 Then portname = "# HA cluster general services"
If theport = 5302 Then portname = "# HA cluster configuration"
If theport = 5303 Then portname = "# HA cluster probing"
If theport = 5304 Then portname = "# HA Cluster Commands"
If theport = 5305 Then portname = "# HA Cluster Test"
If theport = 5400 Then portname = "Excerpt Search"
If theport = 5401 Then portname = "Excerpt Search Secure"
If theport = 5555 Then portname = "Personal Agent"
If theport = 5631 Then portname = "pcANYWHEREdata"
If theport = 5632 Then portname = "pcANYWHEREstat"
If theport = 5678 Then portname = "Remote Replication Agent Connection"
If theport = 5679 Then portname = "Direct Cable Connect Manager"
If theport = 5713 Then portname = "proshare conf audio"
If theport = 5714 Then portname = "proshare conf video"
If theport = 5715 Then portname = "proshare conf data"
If theport = 5716 Then portname = "proshare conf request"
If theport = 5717 Then portname = "proshare conf notify"
If theport = 5729 Then portname = "Openmail User Agent Layer"
If theport = 5742 Then portname = "Wincrash V1.03"
If theport = 5745 Then portname = "fcopy-server"
If theport = 5755 Then portname = "OpenMail Desk Gateway server"
If theport = 5757 Then portname = "OpenMail X.500 Directory Server"
If theport = 5766 Then portname = "OpenMail NewMail Server"
If theport = 5767 Then portname = "OpenMail Suer Agent Layer (Secure)"
If theport = 5800 Then portname = "Virtual Network Computing server"
If theport = 5900 Then portname = "Virtual Network Computing server"
If theport = 6000 Then portname = "6000-6063   X Window System"
If theport = 6110 Then portname = "HP SoftBench CM"
If theport = 6111 Then portname = "HP SoftBench Sub-Process Control"
If theport = 6112 Then portname = "dtspcd"
If theport = 6123 Then portname = "Backup Express"
If theport = 6141 Then portname = "Meta Corporation License Manager"
If theport = 6142 Then portname = "Aspen Technology License Manager"
If theport = 6143 Then portname = "Watershed License Manager"
If theport = 6144 Then portname = "StatSci License Manager - 1"
If theport = 6145 Then portname = "StatSci License Manager - 2"
If theport = 6146 Then portname = "Lone Wolf Systems License Manager"
If theport = 6147 Then portname = "Montage License Manager"
If theport = 6148 Then portname = "Ricardo North America License Manager"
If theport = 6149 Then portname = "tal-pod"
If theport = 6253 Then portname = "CRIP"
If theport = 6389 Then portname = "clariion-evr01"
If theport = 6455 Then portname = "SKIP Certificate Receive"
If theport = 6456 Then portname = "SKIP Certificate Send"
If theport = 6558 Then portname = "?"
If theport = 6588 Then portname = "AnalogX Web Proxy"
If theport = 6670 Then portname = "Vocaltec Global Online Directory"
If theport = 6672 Then portname = "vision_server"
If theport = 6673 Then portname = "vision_elmd"
If theport = 6831 Then portname = "ambit-lm"
If theport = 6969 Then portname = "acmsoda"
If theport = 7000 Then portname = "file server itself"
If theport = 7001 Then portname = "callbacks to cache managers"
If theport = 7002 Then portname = "users & groups database"
If theport = 7003 Then portname = "volume location database"
If theport = 7004 Then portname = "AFS/Kerberos authentication service"
If theport = 7005 Then portname = "volume managment server"
If theport = 7006 Then portname = "error interpretation service"
If theport = 7007 Then portname = "basic overseer process"
If theport = 7008 Then portname = "server-to-server updater"
If theport = 7009 Then portname = "remote cache manager service"
If theport = 7010 Then portname = "onlinet uninterruptable power supplies"
If theport = 7099 Then portname = "lazy-ptop"
If theport = 7100 Then portname = "X Font Service"
If theport = 7121 Then portname = "Virtual Prototypes License Manager"
If theport = 7174 Then portname = "Clutild"
If theport = 7200 Then portname = "FODMS FLIP"
If theport = 7201 Then portname = "DLIP"
If theport = 7395 Then portname = "winqedit"
If theport = 7491 Then portname = "telops-lmd"
If theport = 7511 Then portname = "pafec-lm"
If theport = 7777 Then portname = "cbt"
If theport = 7781 Then portname = "accu-lmgr"
If theport = 7999 Then portname = "iRDMI2"
If theport = 8000 Then portname = "iRDMI/Shoutcast Server"
If theport = 8010 Then portname = "Wingate web logfile"
If theport = 8032 Then portname = "ProEd"
If theport = 8080 Then portname = "Standard HTTP Proxy"
If theport = 8450 Then portname = "npmp"
If theport = 8888 Then portname = "NewsEDGE server TCP (TCP 1)"
If theport = 8889 Then portname = "Desktop Data TCP 1"
If theport = 8890 Then portname = "Desktop Data TCP 2"
If theport = 8891 Then portname = "Desktop Data TCP 3: NESS application"
If theport = 8892 Then portname = "Desktop Data TCP 4: FARM product"
If theport = 8893 Then portname = "Desktop Data TCP 5: NewsEDGE/Web application"
If theport = 8894 Then portname = "Desktop Data TCP 6: COAL application"
If theport = 9000 Then portname = "CSlistener"
If theport = 9100 Then portname = "HP JetDirect Printer Server"
If theport = 9535 Then portname = "?"
If theport = 9876 Then portname = "Session Director"
If theport = 9992 Then portname = "Palace"
If theport = 9993 Then portname = "Palace"
If theport = 9994 Then portname = "Palace"
If theport = 9995 Then portname = "Palace"
If theport = 9996 Then portname = "Palace"
If theport = 9997 Then portname = "Palace"
If theport = 9998 Then portname = "Distinct32"
If theport = 9999 Then portname = "distinct"
If theport = 10000 Then portname = "Network Data Management Protocol"
If theport = 11000 Then portname = "SSTROJG trojan"
If theport = 12345 Then portname = "Win95/NT Netbus backdoor"
If theport = 12753 Then portname = "tsaf port"
If theport = 13223 Then portname = "PowWow chat program"
If theport = 17007 Then portname = "?"
If theport = 18000 Then portname = "Beckman Instruments"
If theport = 20001 Then portname = "Millenium trojan"
If theport = 20024 Then portname = "Netbus 2.0 Pro"
If theport = 21554 Then portname = "GirlFriend trojan"
If theport = 21845 Then portname = "webphone"
If theport = 21846 Then portname = "NetSpeak Corp. Directory Services"
If theport = 21847 Then portname = "NetSpeak Corp. Connection Services"
If theport = 21848 Then portname = "NetSpeak Corp. Automatic Call Distribution"
If theport = 21849 Then portname = "NetSpeak Corp. Credit Processing System"
If theport = 22273 Then portname = "wnn6"
If theport = 22347 Then portname = "WIBU dongle server"
If theport = 22555 Then portname = "Vocaltec Web Conference"
If theport = 22800 Then portname = "Telerate Information Platform LAN"
If theport = 22951 Then portname = "Telerate Information Platform WAN"
If theport = 23456 Then portname = "Evil FTP trojan"
If theport = 25000 Then portname = "icl-twobase1"
If theport = 25001 Then portname = "icl-twobase2"
If theport = 25002 Then portname = "icl-twobase3"
If theport = 25003 Then portname = "icl-twobase4"
If theport = 25004 Then portname = "icl-twobase5"
If theport = 25005 Then portname = "icl-twobase6"
If theport = 25006 Then portname = "icl-twobase7"
If theport = 25007 Then portname = "icl-twobase8"
If theport = 25008 Then portname = "icl-twobase9"
If theport = 25009 Then portname = "icl-twobase10"
If theport = 25793 Then portname = "Vocaltec Address Server"
If theport = 25867 Then portname = "WebCam32 Admin"
If theport = 26000 Then portname = "quake"
If theport = 26208 Then portname = "wnn6-ds"
If theport = 30303 Then portname = "Sockets De Troie trojan"
If theport = 47557 Then portname = "Databeam Corporation"
If theport = 47806 Then portname = "ALC Protocol"
If theport = 47808 Then portname = "Building Automation and Control Networks"
If theport = 54320 Then portname = "Back Orifice 2000"
If theport = 65000 Then portname = "Devil trojan"

End Function

